/* Card & journal art: real photos when present (TREES[id].photos — the mandated
   final art), botanically-shaped vector fallback otherwise. The 13 v1 leaf paths
   are ported verbatim (all verified at 58px in v1); the 13 v2 paths await the
   combined photo/58px pass. Silhouette tier renders the same path in dark fill. */
import { TREES } from '../core/trees';
import { PHOTOS } from '../core/photos.generated';

/* Real photos take precedence over TREES[id].photos (owner-supplied) and both
   over vector art. Fetched photos live in PHOTOS (generated by fetch-photos.mjs). */
function photoFor(id: string): { leaf?: string; bark?: string; tree?: string } | undefined {
  return PHOTOS[id] || TREES[id]?.photos;
}

type Ctx = CanvasRenderingContext2D;
type PathFn = (c: Ctx, cx: number, cy: number, s: number) => void;

/* ---------- v1 paths (verbatim) ---------- */
function pathOakLeaf(c: Ctx, cx: number, cy: number, s: number) {
  const lobes = 3;
  c.beginPath(); c.moveTo(cx, cy - .44 * s);
  for (let i = 0; i < lobes; i++) { const y1 = cy - .44 * s + ((i + .5) / lobes) * .80 * s, y2 = cy - .44 * s + ((i + 1) / lobes) * .80 * s, bulge = .40 * s - i * .03 * s; c.quadraticCurveTo(cx + bulge, y1 - .02 * s, cx + .13 * s, y2); }
  c.lineTo(cx + .06 * s, cy + .42 * s); c.lineTo(cx, cy + .5 * s); c.lineTo(cx - .06 * s, cy + .42 * s);
  for (let i = lobes - 1; i >= 0; i--) { const y2 = cy - .44 * s + (i / lobes) * .80 * s, y1 = cy - .44 * s + ((i + .5) / lobes) * .80 * s, bulge = .40 * s - i * .03 * s; c.quadraticCurveTo(cx - bulge, y1 - .02 * s, cx - .13 * s, y2); }
  c.closePath();
}
function pathPlaneLeaf(c: Ctx, cx: number, cy: number, s: number) {
  c.beginPath(); c.moveTo(cx, cy - .54 * s);
  c.quadraticCurveTo(cx + .09 * s, cy - .28 * s, cx + .09 * s, cy - .16 * s); c.lineTo(cx + .40 * s, cy - .38 * s);
  c.quadraticCurveTo(cx + .32 * s, cy - .06 * s, cx + .22 * s, cy + .02 * s); c.lineTo(cx + .46 * s, cy + .16 * s);
  c.quadraticCurveTo(cx + .26 * s, cy + .18 * s, cx + .11 * s, cy + .32 * s); c.lineTo(cx, cy + .48 * s); c.lineTo(cx - .11 * s, cy + .32 * s);
  c.quadraticCurveTo(cx - .26 * s, cy + .18 * s, cx - .46 * s, cy + .16 * s); c.lineTo(cx - .22 * s, cy + .02 * s);
  c.quadraticCurveTo(cx - .32 * s, cy - .06 * s, cx - .40 * s, cy - .38 * s); c.lineTo(cx - .09 * s, cy - .16 * s);
  c.quadraticCurveTo(cx - .09 * s, cy - .28 * s, cx, cy - .54 * s); c.closePath();
}
function pathLindenLeaf(c: Ctx, cx: number, cy: number, s: number) {
  c.beginPath(); c.moveTo(cx + .02 * s, cy - .48 * s);
  c.quadraticCurveTo(cx + .32 * s, cy - .22 * s, cx + .32 * s, cy + .04 * s); c.quadraticCurveTo(cx + .32 * s, cy + .30 * s, cx + .05 * s, cy + .30 * s);
  c.quadraticCurveTo(cx - .06 * s, cy + .35 * s, cx - .16 * s, cy + .25 * s); c.quadraticCurveTo(cx - .38 * s, cy + .20 * s, cx - .36 * s, cy - .04 * s);
  c.quadraticCurveTo(cx - .33 * s, cy - .26 * s, cx - .10 * s, cy - .40 * s); c.quadraticCurveTo(cx - .04 * s, cy - .45 * s, cx + .02 * s, cy - .48 * s);
  c.closePath();
}
function pathPineLeaf(c: Ctx, cx: number, cy: number, s: number) {
  c.beginPath(); const n = 9;
  for (let i = 0; i < n; i++) {
    const a = -Math.PI / 2 + (i - (n - 1) / 2) * (Math.PI * 0.95 / n);
    const tx = cx + Math.cos(a) * .52 * s, ty = cy + Math.sin(a) * .52 * s;
    const blx = cx + Math.cos(a - .045) * .07 * s, bly = cy + Math.sin(a - .045) * .07 * s + .28 * s;
    const brx = cx + Math.cos(a + .045) * .07 * s, bry = cy + Math.sin(a + .045) * .07 * s + .28 * s;
    c.moveTo(blx, bly); c.lineTo(tx, ty); c.lineTo(brx, bry); c.closePath();
  }
}
function pathCypressLeaf(c: Ctx, cx: number, cy: number, s: number) {
  c.beginPath(); const segs = 10;
  c.moveTo(cx, cy - .48 * s);
  for (let i = 1; i <= segs; i++) { const yy = cy - .48 * s + (i / segs) * .94 * s, width = .16 * s * Math.pow(Math.sin((i / segs) * Math.PI), 0.6), jag = .03 * s * (i % 2 === 0 ? 1 : -1); c.lineTo(cx + width + jag, yy); }
  for (let i = segs; i >= 0; i--) { const yy = cy - .48 * s + (i / segs) * .94 * s, width = .16 * s * Math.pow(Math.sin((i / segs) * Math.PI), 0.6), jag = .03 * s * (i % 2 === 0 ? 1 : -1); c.lineTo(cx - width + jag, yy); }
  c.closePath();
}
function quadSample(base: number[][], p0: number[], cp: number[], p1: number[], n: number) {
  for (let i = 1; i <= n; i++) { const tt = i / n, x = (1 - tt) * (1 - tt) * p0[0] + 2 * (1 - tt) * tt * cp[0] + tt * tt * p1[0], y = (1 - tt) * (1 - tt) * p0[1] + 2 * (1 - tt) * tt * cp[1] + tt * tt * p1[1]; base.push([x, y]); }
}
function pathBirchLeaf(c: Ctx, cx: number, cy: number, s: number) {
  const base: number[][] = [];
  let cur = [cx, cy - .44 * s]; base.push(cur);
  const steps = [[[cx + .26 * s, cy - .22 * s], [cx + .28 * s, cy + .04 * s]], [[cx + .26 * s, cy + .26 * s], [cx + .08 * s, cy + .36 * s]], [[cx, cy + .4 * s], [cx, cy + .42 * s]],
    [[cx, cy + .4 * s], [cx - .08 * s, cy + .36 * s]], [[cx - .26 * s, cy + .26 * s], [cx - .28 * s, cy + .04 * s]], [[cx - .26 * s, cy - .22 * s], [cx, cy - .44 * s]]];
  for (const st of steps) { quadSample(base, cur, st[0], st[1], 10); cur = st[1]; }
  c.beginPath();
  base.forEach((p, i) => { const dx = p[0] - cx, dy = p[1] - cy, d = Math.hypot(dx, dy) || 1, tooth = 1 + ((i % 3 === 0) ? .045 : 0); const x = cx + dx / d * d * tooth, y = cy + dy / d * d * tooth; if (i === 0) c.moveTo(x, y); else c.lineTo(x, y); });
  c.closePath();
}
function pathMapleLeaf(c: Ctx, cx: number, cy: number, s: number) {
  const n = 5, tipR = .5, valleyR = .2;
  c.beginPath();
  for (let i = 0; i < n; i++) {
    const aTip = -Math.PI / 2 + i * (2 * Math.PI / n), aPrevV = aTip - Math.PI / n, aNextV = aTip + Math.PI / n;
    const pv = [cx + Math.cos(aPrevV) * valleyR * s, cy + Math.sin(aPrevV) * valleyR * s];
    const tip = [cx + Math.cos(aTip) * tipR * s, cy + Math.sin(aTip) * tipR * s];
    const nv = [cx + Math.cos(aNextV) * valleyR * s, cy + Math.sin(aNextV) * valleyR * s];
    const cp1 = [cx + Math.cos((aPrevV + aTip) / 2) * tipR * s * .7, cy + Math.sin((aPrevV + aTip) / 2) * tipR * s * .7];
    const cp2 = [cx + Math.cos((aTip + aNextV) / 2) * tipR * s * .7, cy + Math.sin((aTip + aNextV) / 2) * tipR * s * .7];
    if (i === 0) c.moveTo(pv[0], pv[1]);
    c.quadraticCurveTo(cp1[0], cp1[1], tip[0], tip[1]); c.quadraticCurveTo(cp2[0], cp2[1], nv[0], nv[1]);
  }
  c.closePath();
}
function pathWillowLeaf(c: Ctx, cx: number, cy: number, s: number) {
  c.beginPath(); c.moveTo(cx, cy - .5 * s);
  c.quadraticCurveTo(cx + .07 * s, cy - .3 * s, cx + .07 * s, cy - .05 * s); c.quadraticCurveTo(cx + .07 * s, cy + .25 * s, cx + .03 * s, cy + .42 * s);
  c.quadraticCurveTo(cx + .01 * s, cy + .48 * s, cx, cy + .5 * s);
  c.quadraticCurveTo(cx - .01 * s, cy + .48 * s, cx - .03 * s, cy + .42 * s); c.quadraticCurveTo(cx - .07 * s, cy + .25 * s, cx - .07 * s, cy - .05 * s);
  c.quadraticCurveTo(cx - .07 * s, cy - .3 * s, cx, cy - .5 * s); c.closePath();
}
function pathGinkgoLeaf(c: Ctx, cx: number, cy: number, s: number) {
  c.beginPath(); c.moveTo(cx, cy + .42 * s);
  c.quadraticCurveTo(cx - .36 * s, cy + .32 * s, cx - .42 * s, cy - .02 * s); c.quadraticCurveTo(cx - .44 * s, cy - .3 * s, cx - .18 * s, cy - .42 * s);
  c.quadraticCurveTo(cx - .06 * s, cy - .46 * s, cx, cy - .34 * s); c.quadraticCurveTo(cx + .06 * s, cy - .46 * s, cx + .18 * s, cy - .42 * s);
  c.quadraticCurveTo(cx + .44 * s, cy - .3 * s, cx + .42 * s, cy - .02 * s); c.quadraticCurveTo(cx + .36 * s, cy + .32 * s, cx, cy + .42 * s); c.closePath();
}
function pathOliveLeaf(c: Ctx, cx: number, cy: number, s: number) {
  c.beginPath(); c.moveTo(cx, cy - .32 * s);
  c.quadraticCurveTo(cx + .26 * s, cy - .16 * s, cx + .28 * s, cy + .02 * s); c.quadraticCurveTo(cx + .24 * s, cy + .24 * s, cx, cy + .34 * s);
  c.quadraticCurveTo(cx - .24 * s, cy + .24 * s, cx - .28 * s, cy + .02 * s); c.quadraticCurveTo(cx - .26 * s, cy - .16 * s, cx, cy - .32 * s); c.closePath();
}
function pathChestnutLeaf(c: Ctx, cx: number, cy: number, s: number) {
  const base: number[][] = [];
  let cur = [cx, cy - .5 * s]; base.push(cur);
  const steps = [[[cx + .14 * s, cy - .3 * s], [cx + .15 * s, cy - .05 * s]], [[cx + .15 * s, cy + .22 * s], [cx + .06 * s, cy + .4 * s]], [[cx + .02 * s, cy + .47 * s], [cx, cy + .5 * s]],
    [[cx - .02 * s, cy + .47 * s], [cx - .06 * s, cy + .4 * s]], [[cx - .15 * s, cy + .22 * s], [cx - .15 * s, cy - .05 * s]], [[cx - .14 * s, cy - .3 * s], [cx, cy - .5 * s]]];
  for (const st of steps) { quadSample(base, cur, st[0], st[1], 10); cur = st[1]; }
  c.beginPath();
  base.forEach((p, i) => { const dx = p[0] - cx, dy = p[1] - cy, d = Math.hypot(dx, dy) || 1, tooth = 1 + ((i % 2 === 0) ? .09 : -.02); const x = cx + dx / d * d * tooth, y = cy + dy / d * d * tooth; if (i === 0) c.moveTo(x, y); else c.lineTo(x, y); });
  c.closePath();
}
function pathBeechLeaf(c: Ctx, cx: number, cy: number, s: number) {
  const base: number[][] = [];
  let cur = [cx, cy - .46 * s]; base.push(cur);
  const steps = [[[cx + .28 * s, cy - .24 * s], [cx + .3 * s, cy + .02 * s]], [[cx + .28 * s, cy + .26 * s], [cx + .1 * s, cy + .38 * s]], [[cx + .02 * s, cy + .43 * s], [cx, cy + .46 * s]],
    [[cx - .02 * s, cy + .43 * s], [cx - .1 * s, cy + .38 * s]], [[cx - .28 * s, cy + .26 * s], [cx - .3 * s, cy + .02 * s]], [[cx - .28 * s, cy - .24 * s], [cx, cy - .46 * s]]];
  for (const st of steps) { quadSample(base, cur, st[0], st[1], 10); cur = st[1]; }
  c.beginPath();
  base.forEach((p, i) => { const dx = p[0] - cx, dy = p[1] - cy, d = Math.hypot(dx, dy) || 1, wob = 1 + .035 * Math.sin(i * 1.3); const x = cx + dx / d * d * wob, y = cy + dy / d * d * wob; if (i === 0) c.moveTo(x, y); else c.lineTo(x, y); });
  c.closePath();
}
function pathPoplarLeaf(c: Ctx, cx: number, cy: number, s: number) {
  c.beginPath(); c.moveTo(cx, cy - .48 * s);
  c.quadraticCurveTo(cx + .34 * s, cy - .06 * s, cx + .38 * s, cy + .06 * s); c.quadraticCurveTo(cx + .2 * s, cy + .3 * s, cx, cy + .44 * s);
  c.quadraticCurveTo(cx - .2 * s, cy + .3 * s, cx - .38 * s, cy + .06 * s); c.quadraticCurveTo(cx - .34 * s, cy - .06 * s, cx, cy - .48 * s); c.closePath();
}

/* ---------- v2 paths (13 new species; pending combined 58px/photo pass) ---------- */
function pathCedarLeaf(c: Ctx, cx: number, cy: number, s: number) { /* needle rosette */
  c.beginPath(); const n = 12;
  for (let i = 0; i < n; i++) {
    const a = (i / n) * Math.PI * 2;
    c.moveTo(cx + Math.cos(a) * .06 * s, cy + Math.sin(a) * .06 * s);
    c.lineTo(cx + Math.cos(a - .05) * .46 * s, cy + Math.sin(a - .05) * .46 * s);
    c.lineTo(cx + Math.cos(a + .08) * .44 * s, cy + Math.sin(a + .08) * .44 * s);
    c.closePath();
  }
}
function pathJuniperLeaf(c: Ctx, cx: number, cy: number, s: number) { /* scaled sprig + berry bumps */
  c.beginPath(); c.moveTo(cx, cy - .46 * s);
  const segs = 7;
  for (let i = 1; i <= segs; i++) { const yy = cy - .46 * s + (i / segs) * .9 * s, w = .12 * s + .07 * s * Math.sin((i / segs) * Math.PI); c.lineTo(cx + w, yy - .04 * s); c.lineTo(cx + .05 * s, yy); }
  for (let i = segs; i >= 1; i--) { const yy = cy - .46 * s + (i / segs) * .9 * s, w = .12 * s + .07 * s * Math.sin((i / segs) * Math.PI); c.lineTo(cx - .05 * s, yy); c.lineTo(cx - w, yy - .04 * s); }
  c.closePath();
  c.moveTo(cx + .3 * s, cy + .3 * s); c.arc(cx + .24 * s, cy + .3 * s, .06 * s, 0, 7);
  c.moveTo(cx - .18 * s, cy + .38 * s); c.arc(cx - .24 * s, cy + .38 * s, .06 * s, 0, 7);
}
function pathSequoiaLeaf(c: Ctx, cx: number, cy: number, s: number) { /* flat feather frond */
  c.beginPath(); c.moveTo(cx, cy - .5 * s);
  const n = 8;
  for (let i = 1; i <= n; i++) { const yy = cy - .5 * s + (i / n) * .95 * s, w = .3 * s * Math.sin((i / n) * Math.PI * .9); c.lineTo(cx + w, yy - .07 * s); c.lineTo(cx + .04 * s, yy); }
  for (let i = n; i >= 1; i--) { const yy = cy - .5 * s + (i / n) * .95 * s, w = .3 * s * Math.sin((i / n) * Math.PI * .9); c.lineTo(cx - .04 * s, yy); c.lineTo(cx - w, yy - .07 * s); }
  c.closePath();
}
function pathAppleLeaf(c: Ctx, cx: number, cy: number, s: number) { /* plump oval, finely toothed */
  c.beginPath(); c.moveTo(cx, cy - .42 * s);
  const pts = 22;
  for (let i = 1; i <= pts; i++) { const a = -Math.PI / 2 + (i / pts) * Math.PI * 2; const rx = .3 * s, ry = .4 * s; const tooth = 1 + ((i % 2) ? .04 : 0); c.lineTo(cx + Math.cos(a) * rx * tooth, cy + Math.sin(a) * ry * tooth); }
  c.closePath();
}
function pathCherryLeaf(c: Ctx, cx: number, cy: number, s: number) { /* oval with drawn-out drip tip */
  c.beginPath(); c.moveTo(cx, cy - .34 * s);
  c.quadraticCurveTo(cx + .3 * s, cy - .18 * s, cx + .26 * s, cy + .08 * s);
  c.quadraticCurveTo(cx + .2 * s, cy + .3 * s, cx + .04 * s, cy + .38 * s);
  c.lineTo(cx, cy + .52 * s); c.lineTo(cx - .04 * s, cy + .38 * s);
  c.quadraticCurveTo(cx - .2 * s, cy + .3 * s, cx - .26 * s, cy + .08 * s);
  c.quadraticCurveTo(cx - .3 * s, cy - .18 * s, cx, cy - .34 * s); c.closePath();
}
function pathWalnutLeaf(c: Ctx, cx: number, cy: number, s: number) { /* pinnate: leaflet pairs on a stem */
  c.beginPath();
  for (let i = 0; i < 3; i++) {
    const yy = cy - .3 * s + i * .28 * s, lw = .22 * s - i * .02 * s;
    c.moveTo(cx + .04 * s, yy); c.quadraticCurveTo(cx + lw, yy - .1 * s, cx + lw + .1 * s, yy); c.quadraticCurveTo(cx + lw, yy + .1 * s, cx + .04 * s, yy);
    c.moveTo(cx - .04 * s, yy); c.quadraticCurveTo(cx - lw, yy - .1 * s, cx - lw - .1 * s, yy); c.quadraticCurveTo(cx - lw, yy + .1 * s, cx - .04 * s, yy);
  }
  c.moveTo(cx, cy + .3 * s); c.quadraticCurveTo(cx + .12 * s, cy + .42 * s, cx, cy + .52 * s); c.quadraticCurveTo(cx - .12 * s, cy + .42 * s, cx, cy + .3 * s);
}
function pathPalmLeaf(c: Ctx, cx: number, cy: number, s: number) { /* fan of blades */
  c.beginPath(); const n = 7;
  for (let i = 0; i < n; i++) {
    const a = -Math.PI / 2 + (i - (n - 1) / 2) * .32;
    c.moveTo(cx, cy + .35 * s);
    c.quadraticCurveTo(cx + Math.cos(a) * .2 * s, cy + .1 * s + Math.sin(a) * .2 * s, cx + Math.cos(a) * .52 * s, cy + Math.sin(a) * .52 * s + .05 * s);
    c.quadraticCurveTo(cx + Math.cos(a + .12) * .2 * s, cy + .12 * s + Math.sin(a) * .2 * s, cx, cy + .35 * s);
    c.closePath();
  }
}
function pathFigLeaf(c: Ctx, cx: number, cy: number, s: number) { /* deep rounded lobes */
  c.beginPath(); c.moveTo(cx, cy - .5 * s);
  c.quadraticCurveTo(cx + .16 * s, cy - .3 * s, cx + .1 * s, cy - .14 * s);
  c.quadraticCurveTo(cx + .42 * s, cy - .3 * s, cx + .4 * s, cy - .02 * s);
  c.quadraticCurveTo(cx + .38 * s, cy + .16 * s, cx + .16 * s, cy + .14 * s);
  c.quadraticCurveTo(cx + .3 * s, cy + .34 * s, cx + .1 * s, cy + .42 * s);
  c.quadraticCurveTo(cx + .03 * s, cy + .45 * s, cx, cy + .42 * s);
  c.quadraticCurveTo(cx - .03 * s, cy + .45 * s, cx - .1 * s, cy + .42 * s);
  c.quadraticCurveTo(cx - .3 * s, cy + .34 * s, cx - .16 * s, cy + .14 * s);
  c.quadraticCurveTo(cx - .38 * s, cy + .16 * s, cx - .4 * s, cy - .02 * s);
  c.quadraticCurveTo(cx - .42 * s, cy - .3 * s, cx - .1 * s, cy - .14 * s);
  c.quadraticCurveTo(cx - .16 * s, cy - .3 * s, cx, cy - .5 * s); c.closePath();
}
function pathLemonLeaf(c: Ctx, cx: number, cy: number, s: number) { /* glossy ellipse + winged petiole notch */
  c.beginPath(); c.moveTo(cx, cy - .44 * s);
  c.quadraticCurveTo(cx + .3 * s, cy - .26 * s, cx + .28 * s, cy);
  c.quadraticCurveTo(cx + .26 * s, cy + .26 * s, cx, cy + .34 * s);
  c.lineTo(cx + .08 * s, cy + .42 * s); c.lineTo(cx, cy + .5 * s); c.lineTo(cx - .08 * s, cy + .42 * s); c.lineTo(cx, cy + .34 * s);
  c.quadraticCurveTo(cx - .26 * s, cy + .26 * s, cx - .28 * s, cy);
  c.quadraticCurveTo(cx - .3 * s, cy - .26 * s, cx, cy - .44 * s); c.closePath();
}
function pathSpruceLeaf(c: Ctx, cx: number, cy: number, s: number) { /* short stiff needles both sides of twig */
  c.beginPath();
  c.moveTo(cx, cy - .5 * s); c.lineTo(cx + .02 * s, cy + .5 * s); c.lineTo(cx - .02 * s, cy + .5 * s); c.closePath();
  const n = 6;
  for (let i = 0; i < n; i++) {
    const yy = cy - .4 * s + (i / (n - 1)) * .8 * s, len = .26 * s - Math.abs(i - (n - 1) / 2) * .02 * s;
    c.moveTo(cx, yy); c.lineTo(cx + len, yy - .14 * s); c.lineTo(cx + len - .04 * s, yy - .08 * s); c.closePath();
    c.moveTo(cx, yy); c.lineTo(cx - len, yy - .14 * s); c.lineTo(cx - len + .04 * s, yy - .08 * s); c.closePath();
  }
}
function pathHazelLeaf(c: Ctx, cx: number, cy: number, s: number) { /* near-round, doubly toothed, notched tip */
  c.beginPath(); const pts = 20;
  c.moveTo(cx, cy - .46 * s);
  for (let i = 1; i <= pts; i++) { const a = -Math.PI / 2 + (i / pts) * Math.PI * 2; const r = (.36 + .04 * Math.sin(a * 2)) * s * (1 + ((i % 2) ? .05 : -.01)); c.lineTo(cx + Math.cos(a) * r, cy + Math.sin(a) * r * 1.12); }
  c.closePath();
}
function pathAlderLeaf(c: Ctx, cx: number, cy: number, s: number) { /* obovate with blunt/indented top */
  c.beginPath(); c.moveTo(cx - .12 * s, cy - .38 * s);
  c.quadraticCurveTo(cx, cy - .32 * s, cx + .12 * s, cy - .38 * s);
  c.quadraticCurveTo(cx + .36 * s, cy - .2 * s, cx + .3 * s, cy + .08 * s);
  c.quadraticCurveTo(cx + .22 * s, cy + .34 * s, cx, cy + .42 * s);
  c.quadraticCurveTo(cx - .22 * s, cy + .34 * s, cx - .3 * s, cy + .08 * s);
  c.quadraticCurveTo(cx - .36 * s, cy - .2 * s, cx - .12 * s, cy - .38 * s); c.closePath();
}
function pathAshLeaf(c: Ctx, cx: number, cy: number, s: number) { /* pinnate: slimmer leaflets + terminal leaflet */
  c.beginPath();
  for (let i = 0; i < 3; i++) {
    const yy = cy - .26 * s + i * .24 * s, lw = .26 * s;
    c.moveTo(cx + .03 * s, yy); c.quadraticCurveTo(cx + lw * .6, yy - .07 * s, cx + lw, yy - .02 * s); c.quadraticCurveTo(cx + lw * .6, yy + .05 * s, cx + .03 * s, yy);
    c.moveTo(cx - .03 * s, yy); c.quadraticCurveTo(cx - lw * .6, yy - .07 * s, cx - lw, yy - .02 * s); c.quadraticCurveTo(cx - lw * .6, yy + .05 * s, cx - .03 * s, yy);
  }
  c.moveTo(cx, cy - .3 * s); c.quadraticCurveTo(cx + .09 * s, cy - .42 * s, cx, cy - .52 * s); c.quadraticCurveTo(cx - .09 * s, cy - .42 * s, cx, cy - .3 * s);
}

export const LEAF_PATH: Record<string, PathFn> = {
  'meşe': pathOakLeaf, 'çınar': pathPlaneLeaf, 'ıhlamur': pathLindenLeaf,
  'çam': pathPineLeaf, 'servi': pathCypressLeaf, 'huş': pathBirchLeaf, 'akçaağaç': pathMapleLeaf,
  'söğüt': pathWillowLeaf, 'ginkgo': pathGinkgoLeaf, 'zeytin': pathOliveLeaf,
  'kestane': pathChestnutLeaf, 'kayın': pathBeechLeaf, 'kavak': pathPoplarLeaf,
  'toros sediri': pathCedarLeaf, 'ardıç': pathJuniperLeaf, 'sekoya': pathSequoiaLeaf,
  'elma': pathAppleLeaf, 'kiraz': pathCherryLeaf, 'ceviz': pathWalnutLeaf,
  'palmiye': pathPalmLeaf, 'incir': pathFigLeaf, 'limon': pathLemonLeaf,
  'ladin': pathSpruceLeaf, 'fındık': pathHazelLeaf, 'kızılağaç': pathAlderLeaf, 'dişbudak': pathAshLeaf,
};

export const LEAF_COLOR: Record<string, [string, string]> = {
  'meşe': ['#4f9e63', '#356e45'], 'çınar': ['#7cc257', '#4f8a38'], 'ıhlamur': ['#93dc9e', '#5ba368'],
  'çam': ['#4a8a5c', '#2f6b41'], 'servi': ['#4a9a78', '#2f7858'], 'huş': ['#a3d178', '#7cae55'], 'akçaağaç': ['#8ec24e', '#699934'],
  'söğüt': ['#9fc47a', '#7aa354'], 'ginkgo': ['#cec257', '#a8a13e'], 'zeytin': ['#9aab6e', '#7c8f52'],
  'kestane': ['#8bb04e', '#5e8a36'], 'kayın': ['#8fc45e', '#679c3e'], 'kavak': ['#a6d074', '#7cab4e'],
  'toros sediri': ['#3f7a5c', '#2a5a42'], 'ardıç': ['#5c8a6e', '#3f6b52'], 'sekoya': ['#4f8a52', '#356b3a'],
  'elma': ['#6fb455', '#4c8a3a'], 'kiraz': ['#5faa62', '#3f7d44'], 'ceviz': ['#7ca85c', '#5a833f'],
  'palmiye': ['#4fa876', '#348a58'], 'incir': ['#5c9a4f', '#3f7a36'], 'limon': ['#4f9a44', '#357a2e'],
  'ladin': ['#33695c', '#224d42'], 'fındık': ['#84b45c', '#5f8f3e'], 'kızılağaç': ['#6ba05c', '#4c7f40'], 'dişbudak': ['#75ad68', '#548a48'],
};

export function drawBarkSwatch(c: Ctx, x: number, y: number, w: number, h: number, species: string): void {
  if (species === 'meşe' || species === 'ceviz' || species === 'dişbudak') {
    c.fillStyle = species === 'meşe' ? '#4a3f36' : species === 'ceviz' ? '#5d5248' : '#6f6a5a'; c.fillRect(x, y, w, h); c.strokeStyle = '#2e2620'; c.lineWidth = 1.3;
    for (let i = 2; i < w; i += 5) { c.beginPath(); const jx = x + i + Math.sin(i * .7) * 1.4; c.moveTo(jx, y); c.lineTo(jx + Math.sin(i * 1.3) * 2, y + h); c.stroke(); }
  } else if (species === 'çınar') {
    c.fillStyle = '#cdbd90'; c.fillRect(x, y, w, h);
    const pal = ['#8a9a5b', '#a9895c', '#e8dcc0', '#8a9a5b', '#c9b98a']; let seed = 7;
    for (let i = 0; i < 9; i++) {
      seed = (seed * 9301 + 49297) % 233280; const rx = x + (seed / 233280) * w;
      seed = (seed * 9301 + 49297) % 233280; const ry = y + (seed / 233280) * h;
      seed = (seed * 9301 + 49297) % 233280; const rr = 2.6 + (seed / 233280) * 4;
      c.fillStyle = pal[i % pal.length]; c.beginPath(); c.ellipse(rx, ry, rr, rr * .72, 0, 0, 7); c.fill();
    }
  } else if (species === 'huş' || species === 'kiraz') {
    c.fillStyle = species === 'huş' ? '#e8e2d4' : '#8a5a4a'; c.fillRect(x, y, w, h); c.strokeStyle = species === 'huş' ? '#3a352c' : '#5c3a30'; c.lineWidth = 1.4;
    let seed = 13; for (let i = 0; i < 6; i++) {
      seed = (seed * 9301 + 49297) % 233280; const ry = y + (seed / 233280) * h;
      seed = (seed * 9301 + 49297) % 233280; const rx = x + (seed / 233280) * w * .8; const rw = 4 + ((seed >> 3) % 6);
      c.beginPath(); c.moveTo(rx, ry); c.lineTo(rx + rw, ry + 1); c.stroke();
    }
  } else if (['çam', 'servi', 'toros sediri', 'ardıç', 'ladin'].includes(species)) {
    c.fillStyle = '#6b4a35'; c.fillRect(x, y, w, h); c.strokeStyle = '#48301f'; c.lineWidth = 1.2;
    for (let i = 2; i < w; i += 4) { c.beginPath(); const jx = x + i + Math.sin(i * .9) * 1; c.moveTo(jx, y); c.lineTo(jx + 1, y + h); c.stroke(); }
  } else if (species === 'sekoya') {
    c.fillStyle = '#8a4a30'; c.fillRect(x, y, w, h); c.strokeStyle = '#6b3520'; c.lineWidth = 2;
    for (let i = 3; i < w; i += 6) { c.beginPath(); c.moveTo(x + i, y); c.lineTo(x + i + 2, y + h); c.stroke(); }
  } else if (species === 'kayın') {
    c.fillStyle = '#9a9184'; c.fillRect(x, y, w, h); c.strokeStyle = '#7d7568'; c.lineWidth = 1;
    for (let i = 4; i < w; i += 10) { c.beginPath(); c.moveTo(x + i, y + 2); c.lineTo(x + i, y + h - 2); c.stroke(); }
  } else if (species === 'palmiye') {
    c.fillStyle = '#9a8a6a'; c.fillRect(x, y, w, h); c.strokeStyle = '#7a6a4a'; c.lineWidth = 1.4;
    for (let yy = y + 2; yy < y + h; yy += 4) { c.beginPath(); c.moveTo(x, yy); c.lineTo(x + w, yy + 2); c.stroke(); }
  } else {
    c.fillStyle = '#8a8478'; c.fillRect(x, y, w, h); c.strokeStyle = '#6f6a5f'; c.lineWidth = 1;
    for (let i = 3; i < w; i += 8) { c.beginPath(); c.moveTo(x + i, y); c.lineTo(x + i, y + h); c.stroke(); }
  }
}

const iconCache: Record<string, string> = {};

/* Vector leaf icon (gradient fill + veins + stem, optional bark strip) — v1 port. */
export function getTreeIcon(species: string, size: number, withBark = true): string {
  const key = `${species}:${size}:${withBark}`;
  if (iconCache[key]) return iconCache[key];
  const cv = document.createElement('canvas');
  cv.width = size; cv.height = Math.round(withBark ? size * 1.32 : size * 1.08);
  const c = cv.getContext('2d')!;
  const cx = size / 2, cy = size * .46, s = size * .86;
  const pathFn = LEAF_PATH[species] || LEAF_PATH['meşe'];
  const cols = LEAF_COLOR[species] || LEAF_COLOR['meşe'];
  c.strokeStyle = '#6b5a3a'; c.lineWidth = Math.max(1.6, size * .03); c.lineCap = 'round';
  c.beginPath(); c.moveTo(cx, cy + .42 * s); c.quadraticCurveTo(cx + .03 * s, cy + .5 * s, cx - .02 * s, cy + .56 * s); c.stroke();
  pathFn(c, cx, cy, s);
  const lg = c.createLinearGradient(cx - .4 * s, cy - .4 * s, cx + .4 * s, cy + .4 * s);
  lg.addColorStop(0, cols[0]); lg.addColorStop(1, cols[1]);
  c.fillStyle = lg; c.fill();
  c.strokeStyle = 'rgba(20,50,35,.45)'; c.lineWidth = Math.max(1.1, size * .018); c.stroke();
  c.save(); pathFn(c, cx, cy, s); c.clip();
  c.strokeStyle = 'rgba(255,255,255,.5)'; c.lineWidth = Math.max(1, size * .016); c.lineCap = 'round';
  c.beginPath(); c.moveTo(cx, cy - .42 * s); c.lineTo(cx, cy + .42 * s); c.stroke();
  c.lineWidth = Math.max(.8, size * .011);
  for (let i = 0; i < 4; i++) {
    const vy = cy - .30 * s + i * .19 * s;
    c.beginPath(); c.moveTo(cx, vy); c.quadraticCurveTo(cx + .16 * s, vy + .02 * s, cx + .30 * s, vy - .07 * s); c.stroke();
    c.beginPath(); c.moveTo(cx, vy); c.quadraticCurveTo(cx - .16 * s, vy + .02 * s, cx - .30 * s, vy - .07 * s); c.stroke();
  }
  c.restore();
  if (withBark) drawBarkSwatch(c, size * .14, size * 1.12, size * .72, size * .14, species);
  const url = cv.toDataURL(); iconCache[key] = url; return url;
}

/* Silhouette icon: same botanical path, near-black fill — the mastery clue tier. */
export function getTreeSilhouette(species: string, size: number): string {
  const key = `sil:${species}:${size}`;
  if (iconCache[key]) return iconCache[key];
  const cv = document.createElement('canvas');
  cv.width = size; cv.height = Math.round(size * 1.08);
  const c = cv.getContext('2d')!;
  const pathFn = LEAF_PATH[species] || LEAF_PATH['meşe'];
  pathFn(c, size / 2, size * .5, size * .86);
  c.fillStyle = '#233a33'; c.fill();
  const url = cv.toDataURL(); iconCache[key] = url; return url;
}

/* Bark-only clue: species bark texture as a large swatch. */
export function getBarkClue(species: string, size: number): string {
  const key = `bark:${species}:${size}`;
  if (iconCache[key]) return iconCache[key];
  const cv = document.createElement('canvas');
  cv.width = size; cv.height = size;
  const c = cv.getContext('2d')!;
  drawBarkSwatch(c, 0, 0, size, size, species);
  const url = cv.toDataURL(); iconCache[key] = url; return url;
}

export type ClueKind = 'leaf' | 'bark' | 'silhouette';

/* Art resolver — REAL PHOTOS FIRST (the mandated card art), vector fallback. */
export function getTreeArt(id: string, kind: ClueKind, size: number): string {
  const photos = photoFor(id);
  if (photos) {
    if (kind === 'leaf' && photos.leaf) return photos.leaf;
    if (kind === 'bark' && photos.bark) return photos.bark;
    if (kind === 'silhouette' && photos.tree) return photos.tree;
  }
  if (kind === 'bark') return getBarkClue(id, size);
  if (kind === 'silhouette') return getTreeSilhouette(id, size);
  return getTreeIcon(id, size, false);
}
/* Choice-card art (leaf + bark strip, or photo). */
export function getChoiceArt(id: string, size: number): string {
  const photos = photoFor(id);
  if (photos?.leaf) return photos.leaf;
  return getTreeIcon(id, size, true);
}
