/* AUTO-GENERATED by scripts/fetch-photos.mjs. Do not edit by hand.
   Maps tree id -> real photo paths (leaf/bark/tree). Empty until photos are fetched. */
export const PHOTOS: Record<string, { leaf?: string; bark?: string; tree?: string }> = {
  "meşe": {
    "leaf": "./photos/meşe_leaf.webp",
    "bark": "./photos/meşe_bark.webp",
    "tree": "./photos/meşe_tree.webp"
  },
  "çınar": {
    "leaf": "./photos/çınar_leaf.webp",
    "bark": "./photos/çınar_bark.webp",
    "tree": "./photos/çınar_tree.webp"
  },
  "ıhlamur": {
    "leaf": "./photos/ıhlamur_leaf.webp",
    "bark": "./photos/ıhlamur_bark.webp",
    "tree": "./photos/ıhlamur_tree.webp"
  }
};
