/* AUTO-GENERATED by scripts/fetch-photos.mjs. Do not edit by hand.
   Maps tree id -> real photo paths (leaf/bark/tree). Empty until photos are fetched.
   Committed empty so the game builds with vector fallback; running the fetch script
   overwrites this with real photo paths and the cards switch to photos automatically. */
export const PHOTOS: Record<string, { leaf?: string; bark?: string; tree?: string }> = {};
