/* Download vetted CC0/PD tree photos from Wikimedia Commons, crop + WebP-encode,
   and generate the runtime photo manifest the game reads.
   Run on a machine WITH network (your Mac): `node scripts/fetch-photos.mjs`
   Requires: `npm i -D sharp` (only needed for this script, not the game).

   Why a script instead of committed binaries: keeps provenance auditable, avoids
   bloating git with ~1MB of images, and lets you swap in your own licensed photos
   by editing scripts/photo-manifest.json and rerunning. */
import { readFile, writeFile, mkdir } from 'node:fs/promises';
import { existsSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.join(__dirname, '..');
const OUT_DIR = path.join(ROOT, 'public', 'photos');
const MANIFEST = path.join(__dirname, 'photo-manifest.json');
const GEN_TS = path.join(ROOT, 'src', 'core', 'photos.generated.ts');

const SIZES = { leaf: [440, 440], bark: [440, 440], tree: [390, 520] };
const UA = 'CokKalpliKoruyucu-photo-fetch/1.0 (game asset pipeline; contact repo owner)';

let sharp;
try { sharp = (await import('sharp')).default; }
catch { console.error('Missing dependency: run  npm i -D sharp  then rerun.'); process.exit(1); }

function commonsUrl(file, width) {
  return `https://commons.wikimedia.org/wiki/Special:Redirect/file/${encodeURIComponent(file)}?width=${width}`;
}

const sleep = (ms) => new Promise(r => setTimeout(r, ms));

/* Commons rate-limits rapid sequential requests (HTTP 429). Be polite: throttle
   between requests and retry on 429/5xx with backoff, honoring Retry-After. */
async function fetchBuffer(file, attempt = 0) {
  const res = await fetch(commonsUrl(file, 1200), { headers: { 'User-Agent': UA }, redirect: 'follow' });
  if (res.ok) return Buffer.from(await res.arrayBuffer());
  if ((res.status === 429 || res.status >= 500) && attempt < 5) {
    const retryAfter = Number(res.headers.get('retry-after'));
    const wait = Number.isFinite(retryAfter) && retryAfter > 0 ? retryAfter * 1000 : 2000 * 2 ** attempt;
    console.warn(`  … ${res.status} for ${file}, retrying in ${Math.round(wait / 1000)}s (attempt ${attempt + 1}/5)`);
    await sleep(wait);
    return fetchBuffer(file, attempt + 1);
  }
  throw new Error(`HTTP ${res.status} for ${file}`);
}

async function process(species, kind, file) {
  const [w, h] = SIZES[kind];
  const buf = await fetchBuffer(file);
  const outName = `${species}_${kind}.webp`;
  await sharp(buf)
    .resize(w, h, { fit: 'cover', position: 'centre' })
    .webp({ quality: 80 })
    .toFile(path.join(OUT_DIR, outName));
  return outName;
}

async function main() {
  await mkdir(OUT_DIR, { recursive: true });
  const { slots } = JSON.parse(await readFile(MANIFEST, 'utf8'));
  const generated = {}; /* species -> { leaf?, bark?, tree? } of runtime paths */
  for (const [species, kinds] of Object.entries(slots)) {
    generated[species] = {};
    for (const [kind, file] of Object.entries(kinds)) {
      try {
        const name = await process(species, kind, file);
        generated[species][kind] = `./photos/${name}`;
        console.log(`✓ ${species} ${kind} ← ${file}`);
      } catch (e) {
        console.warn(`✗ ${species} ${kind}: ${e.message} (will fall back to vector art)`);
      }
      await sleep(1200); /* throttle: stay under Commons' rate limit */
    }
  }
  const banner = '/* AUTO-GENERATED by scripts/fetch-photos.mjs. Do not edit by hand.\n' +
    '   Maps tree id -> real photo paths (leaf/bark/tree). Empty until photos are fetched. */\n';
  const body = 'export const PHOTOS: Record<string, { leaf?: string; bark?: string; tree?: string }> = ' +
    JSON.stringify(generated, null, 2) + ';\n';
  await writeFile(GEN_TS, banner + body);
  console.log(`\nWrote ${GEN_TS}. Now: npm run build && npx cap sync ios`);
  if (!existsSync(GEN_TS)) process.exit(1);
}
main().catch(e => { console.error(e); process.exit(1); });
